import { defineMessages } from "../defineMessages";

/**
 * Reader "Aa" panel: themes, font size, layout and the detailed typography tab.
 * On phones this is a bottom sheet; segmented buttons are narrow (max ≈ 6–8 chars).
 */
export const aa = defineMessages("aa", {
  "aa.turn.slide": { zh: "滑动", note: "Page-turn animation option.", max: 8 },
  "aa.turn.fade": { zh: "淡入", note: "Page-turn animation option.", max: 8 },
  "aa.turn.none": { zh: "无", note: "Page-turn animation option: none.", max: 8 },
  "aa.theme.light": { zh: "白底", note: "Theme name: white paper.", max: 8 },
  "aa.theme.sepia": { zh: "羊皮纸", note: "Theme name: sepia/parchment.", max: 8 },
  "aa.theme.gray": { zh: "深灰", note: "Theme name: dark gray.", max: 8 },
  "aa.theme.dark": { zh: "暗夜", note: "Theme name: night/black.", max: 8 },
  "aa.theme.tip": { zh: "{name}主题", note: "Tooltip on a theme swatch, e.g. 'Sepia theme'." },
  "aa.lineHeight.compact": { zh: "紧凑", max: 8 },
  "aa.lineHeight.standard": { zh: "标准", max: 8 },
  "aa.lineHeight.loose": { zh: "宽松", max: 8 },
  "aa.margin.auto": { zh: "自动", max: 8 },
  "aa.margin.narrow": { zh: "窄", max: 8 },
  "aa.margin.medium": { zh: "适中", max: 8 },
  "aa.margin.wide": { zh: "宽", max: 8 },
  "aa.auto": { zh: "自动", note: "A value chosen automatically.", max: 10 },
  "aa.autoEffective": { zh: "自动（当前有效 {px}px）", note: "Automatic gap with the value currently in effect." },
  "aa.autoPx": { zh: "自动（{px}px）", note: "Automatic margin with its current pixel value." },
  "aa.followBook": { zh: "跟随书籍", note: "Use the book's own value." },
  "aa.default": { zh: "默认", max: 8 },
  "aa.weight.light": "细体 (300)",
  "aa.weight.regular": "常规 (400)",
  "aa.weight.medium": "中等 (500)",
  "aa.weight.semibold": "半粗 (600)",
  "aa.weight.bold": "粗体 (700)",
  "aa.dialog": "排版与外观设置",
  "aa.tabs": "排版设置模式切换",
  "aa.tab.quick": { zh: "常用外观", max: 12 },
  "aa.tab.detailed": { zh: "详细排版", max: 12 },
  "aa.close.tip": "关闭设置 (Esc)",
  "aa.close": "关闭",
  "aa.group.themeSize": "主题与字号",
  "aa.themes": "主题配色",
  "aa.fontSize": { zh: "字号", max: 10 },
  "aa.fontSize.dec.tip": "减小字号 (最小 12px)",
  "aa.fontSize.dec": "减小字号",
  "aa.fontSize.small": { zh: "小 A", note: "Button glyph: smaller text. Keep the letter A.", max: 4 },
  "aa.fontSize.current": "当前字号 {px}px",
  "aa.fontSize.inc.tip": "增大字号 (最大 32px)",
  "aa.fontSize.inc": "增大字号",
  "aa.fontSize.large": { zh: "大 A", note: "Button glyph: larger text. Keep the letter A.", max: 4 },
  "aa.font": { zh: "字体", max: 10 },
  "aa.font.tip": "配置字体与导入字体",
  "aa.font.default": "系统 / 书籍默认",
  "aa.display": { zh: "显示", max: 10 },
  "aa.display.tip": "字符替换、繁简显示、画面滤镜与色弱辅助",
  "aa.display.open": { zh: "字符与画面", note: "Opens character display and visual filter settings." },
  "aa.group.layout": "排版与版式",
  "aa.lineHeight": { zh: "行高", max: 10 },
  "aa.lineHeight.custom": "当前处于自定义微调值",
  "aa.margins": { zh: "边距", max: 10 },
  "aa.margins.custom.tip": "已启用独立四向微调边距",
  "aa.margins.custom": { zh: "微调", note: "Small pill: margins were fine-tuned.", max: 8 },
  "aa.margins.group": "页边距",
  "aa.presentation": { zh: "排版", note: "Row label: page presentation (single/two-page/scroll).", max: 10 },
  "aa.presentation.group": "排版方式",
  "aa.presentation.single": { zh: "单页", max: 8 },
  "aa.presentation.spread": { zh: "双页", max: 8 },
  "aa.presentation.scroll": { zh: "滚动", max: 8 },
  "aa.presentation.narrow": "窗口较窄，暂以单页显示",
  "aa.group.advanced": "翻页与进阶",
  "aa.turnAnimation": { zh: "翻页动画", max: 14 },
  "aa.detail.open.tip": "展开详细排版参数设置",
  "aa.detail.open": "详细排版微调（字重/间距/四向边距）",
  "aa.more": "更多高级设置",
  "aa.forceHorizontal": "强制竖排转横排",
  "aa.preload": "高性能预读",
  "aa.preload.warning": "对硬件要求较高",
  "aa.css": "自定义 CSS",
  "aa.css.placeholder": { zh: "/* 自定义注入 CSS */", note: "Placeholder inside a CSS editor; keep it a CSS comment." },
  "aa.css.save": "保存并应用 CSS",
  "aa.importBooks.tip": "打开并导入书籍",
  "aa.importBooks": "导入书籍",
  "aa.log.tip": "打开日志与诊断",
  "aa.log": "诊断日志",
  "aa.log.count": { zh: "诊断日志 ({count})", note: "{count} is the number of issues." },
  "aa.reset.tip": "恢复全部设置默认值",
  "aa.reset": { zh: "恢复默认", max: 12 },
  "aa.detail": "详细排版参数",
  "aa.detail.text": "正文精细排版",
  "aa.lineHeight.ratio": "行高倍率",
  "aa.lineHeight.times": { zh: "{value} 倍", note: "Line-height multiplier, e.g. '1.7×'." },
  "aa.lineHeight.auto": "自动 (1.7)",
  "aa.lineHeight.reset.tip": "重置为默认行高 (1.7)",
  "aa.lineHeight.reset": "重置行高",
  "aa.lineHeight.dec": "减小行高",
  "aa.lineHeight.inc": "增大行高",
  "aa.weight": "正文字重",
  "aa.weight.reset.tip": "恢复为书籍默认字重",
  "aa.weight.reset": "重置字重",
  "aa.weight.dec": "调细字重",
  "aa.weight.inc": "调粗字重",
  "aa.letterSpacing": "字间距",
  "aa.letterSpacing.reset.tip": "恢复为书籍默认字间距",
  "aa.letterSpacing.reset": "重置字间距",
  "aa.letterSpacing.dec": "减小字间距",
  "aa.letterSpacing.inc": "增大字间距",
  "aa.wordSpacing": "词间距",
  "aa.wordSpacing.reset.tip": "恢复为书籍默认词间距",
  "aa.wordSpacing.reset": "重置词间距",
  "aa.wordSpacing.dec": "减小词间距",
  "aa.wordSpacing.inc": "增大词间距",
  "aa.detail.margins": "版心与四向留白",
  "aa.margin.top": "上边距",
  "aa.margin.top.auto": "自动 (2.2em)",
  "aa.margin.top.reset.tip": "重置为自动顶部黄金留白",
  "aa.margin.top.reset": "重置上边距",
  "aa.margin.top.dec": "减小上边距",
  "aa.margin.top.inc": "增大上边距",
  "aa.margin.bottom": "下边距",
  "aa.margin.bottom.auto": "自动 (1.6em)",
  "aa.margin.bottom.reset.tip": "重置为自动底部留白",
  "aa.margin.bottom.reset": "重置下边距",
  "aa.margin.bottom.dec": "减小下边距",
  "aa.margin.bottom.inc": "增大下边距",
  "aa.margin.left": "左边距",
  "aa.margin.reset.tip": "重置为自动",
  "aa.margin.left.reset": "重置左边距",
  "aa.margin.left.dec": "减小左边距",
  "aa.margin.left.inc": "增大左边距",
  "aa.margin.right": "右边距",
  "aa.margin.right.reset": "重置右边距",
  "aa.margin.right.dec": "减小右边距",
  "aa.margin.right.inc": "增大右边距",
  "aa.gap": "双栏中缝",
  "aa.gap.spreadOnly": { zh: "{value}（双页生效）", note: "{value} is the gap; it only applies in two-page view." },
  "aa.gap.reset.tip": "重置为自动中缝（保留手动数值）",
  "aa.gap.reset": "重置列间距",
  "aa.gap.dec": "减小双栏中缝",
  "aa.gap.inc": "增大双栏中缝",
  "aa.detail.engine": "界面与引擎",
  "aa.uiScale": "界面缩放",
  "aa.css.inject": "自定义 CSS 样式注入",
  "aa.css.placeholderLong": { zh: "/* 自定义注入 CSS，例：body { text-align: justify !important; } */", note: "Placeholder; keep the CSS example unchanged." },
  "aa.resetAll": "恢复默认设置",
});
