import { defineMessages } from "../defineMessages";

/**
 * AI development panel (AI edition, debug builds; release builds show only the model asset section).
 * Developer-facing wording: keep product and technical terms such as mock, Provider, IndexedDB, SQLite,
 * linked, DirectML, LUID, Top-K and cosine untranslated. Messages produced by AI runtime modules are
 * diagnostics and are not in this catalog.
 */
export const ai = /* @__PURE__ */ defineMessages("ai", {
  "ai.unknown": "未知",
  "ai.cancel": "取消",
  "ai.rebuild": "重建",
  "ai.citation": { zh: "{chapter}：{text}", note: "Index citation button: chapter title, then a text excerpt." },

  "ai.capability.embedding": "向量嵌入",
  "ai.capability.generation": "文本生成",
  "ai.capability.reranking": "重排",
  "ai.state.disabled": "未启用",
  "ai.state.initializing": "准备中",
  "ai.state.error": "异常",
  "ai.state.available": "可用",
  "ai.state.unavailable": "不可用",
  "ai.health.unchecked": "未检查",
  "ai.health.healthy": "健康",
  "ai.health.checking": "检查中",
  "ai.health.degraded": "降级",
  "ai.health.unhealthy": "不健康",
  "ai.panel.title": "AI 与模型（开发）",
  "ai.panel.subtitle": "开发模式能力检查",
  "ai.panel.close": { zh: "关闭 AI 与模型（开发）", note: "Accessible label of the close button." },
  "ai.panel.note.desktop": "能力检查使用 mock；下方索引测试仅在显式开始后读取当前书并写入本机 SQLite，不加载真实模型。",
  "ai.panel.note.browser": "下方可恢复索引使用浏览器 IndexedDB，可直接测试建库、取消、恢复和引用跳转；不加载真实模型。",
  "ai.panel.note.release": "当前发行版只管理模型文件与下载元数据；未启用 Provider，不加载模型、不读取正文、不建向量、不执行推理。",
  "ai.panel.providerHealth": "Provider 健康",
  "ai.panel.enableMock": "启用 mock",
  "ai.panel.disable": "禁用并释放",

  "ai.hw.title": "硬件与资源探测",
  "ai.hw.note.desktop": "主动检查 Windows 设备能力与当前进程的显存预算。模型运行时尚未接入，不加载模型或执行推理。",
  "ai.hw.note.preview": "以下为可切换的预览数据，不代表本机 GPU。真实设备和预算需在 Windows 点击探测。",
  "ai.hw.scenario": "预览场景",
  "ai.hw.scenario.label": { zh: "硬件预览场景", note: "Accessible label of the scenario selector." },
  "ai.hw.scenario.candidate": "正常候选",
  "ai.hw.scenario.unsupported": "设备不支持",
  "ai.hw.scenario.unknownBudget": "预算未知",
  "ai.hw.scenario.lowBudget": "预算不足",
  "ai.hw.scenario.failure": "探测失败",
  "ai.hw.probe": "探测本机硬件",
  "ai.hw.preview": "查看硬件预览",
  "ai.hw.cancel": "取消等待",
  "ai.hw.reserve": "测试预留（MiB）",
  "ai.hw.reserve.label": { zh: "测试预留 MiB", note: "Accessible label of the reserve input." },
  "ai.hw.reserveNote": "只评估预算，不实际分配显存；候选设备可用不等于模型后端已就绪。",
  "ai.hw.result.preview": "预览结果",
  "ai.hw.result.native": "本机探测结果",
  "ai.hw.fit.fits": "可满足测试预留",
  "ai.hw.fit.insufficient": "可用预算不足",
  "ai.hw.fit.unknown": "预算未知，拒绝准入",
  "ai.hw.fit.invalid": "预算或预留值无效，拒绝准入",
  "ai.hw.candidate.available": { zh: "{name}：可用候选", note: "{name} is a GPU backend name." },
  "ai.hw.candidate.unavailable": { zh: "{name}：不可用", note: "{name} is a GPU backend name." },
  "ai.hw.budget": { zh: "进程预算：{budget}；当前使用：{usage}", note: "Values are sizes such as '512.0 MiB'." },
  "ai.hw.headroom": "可用差额：{amount}（动态快照）",
  "ai.hw.source": "来源：{source}",
  "ai.hw.assessment": "预算评估：{label}",
  "ai.hw.admission.pending": "运行准入：尚未接入模型运行时",
  "ai.hw.admission.denied": "运行准入：候选不可用，拒绝准入",

  "ai.lock.title": "共享模型库保护",
  "ai.lock.note.desktop": "下载、校验和删除现已使用文件锁。先在下方选择模型库，再检查共享读取与写入保护；不会加载或删除模型。",
  "ai.lock.note.browser": "浏览器可检查标签页锁的读写互斥与释放。桌面模型库的文件锁需在 Windows 验证。",
  "ai.lock.checking": "检查中…",
  "ai.lock.checkFile": "检查文件锁",
  "ai.lock.checkBrowser": "检查浏览器锁",

  "ai.license.title": "接受模型许可证",
  "ai.license.source": "来源：{source}",
  "ai.license.accept": "接受并继续",

  "ai.assets.title": "模型资产",
  "ai.assets.explanation": "这里只管理模型文件与下载元数据；不会创建或启用 Provider，不加载模型、不读取正文、不建向量、不执行推理。",
  "ai.assets.browserOnly": "浏览器预览需要桌面开发构建才能管理模型资产；当前不会调用 Tauri。",
  "ai.assets.pickDirectory": { zh: "选择模型目录", note: "Title of the system folder picker." },
  "ai.assets.loading": "读取中…",
  "ai.assets.refresh": "刷新元数据",
  "ai.assets.chooseLibrary": "选择模型库",
  "ai.assets.importLinked": "导入 linked 目录",
  "ai.assets.registerTest": "登记测试包",
  "ai.assets.library": "模型库：{path}",
  "ai.assets.notSet": "未设置",
  "ai.assets.empty": "暂无已登记模型资产",
  "ai.assets.capabilities.test": { zh: "测试声明能力：", note: "Followed by a list of capability ids." },
  "ai.assets.capabilities": { zh: "能力：", note: "Followed by a list of capability ids." },
  "ai.assets.linked": "linked：{path}",
  "ai.assets.managed": "受管理目录：{path}",
  "ai.assets.license": "许可证：{license}",
  "ai.assets.download": { zh: "下载：{state} · {progress}", note: "{state} is a technical task state id." },
  "ai.assets.verify": "校验",
  "ai.assets.relocate": "重新定位",
  "ai.assets.pause": "暂停",
  "ai.assets.resume": "继续",
  "ai.assets.retry": "重试",
  "ai.assets.downloadAction": "下载",
  "ai.assets.confirmDeleteManaged": "确认删除登记记录及受管理模型文件？",
  "ai.assets.confirmDeleteLinked": "确认只删除 linked 登记记录？外部文件不会被删除。",
  "ai.assets.deleteFiles": "删除文件与记录",
  "ai.assets.deleteRecord": "删除记录",

  "ai.prep.title": "可恢复 mock 索引（调试）",
  "ai.prep.region": { zh: "可恢复 mock 索引", note: "Accessible label of the section." },
  "ai.prep.note.browser": "当前使用浏览器 IndexedDB：可测试建库、取消、刷新恢复和引用跳转。数据仅保存在当前浏览器，与桌面 SQLite 独立。",
  "ai.prep.note.desktop": "当前使用桌面 SQLite。",
  "ai.prep.note.scope": "仅处理当前书。关闭面板取消任务并保留恢复点；清理只影响本书假向量。预算为注入的测试值，不代表实际硬件探测。",
  "ai.prep.initial": "尚未运行；只使用确定性假向量，没有语义搜索能力。",
  "ai.prep.running": "正在准备 mock 索引；取消或关闭面板会保留恢复点。",
  "ai.prep.done": "mock 索引已完成。下面仅显示前 20 个原文引用，用于核对跳转。",
  "ai.prep.cleared": "本书 mock 索引已清理，全文搜索与模型文件保留。",
  "ai.prep.statusRead": "状态已读取；不会自动开始建库。",
  "ai.prep.cancelled": "已取消；再次继续将校验并复用已保存批次。",
  "ai.prep.fault": "故障注入",
  "ai.prep.fault.none": "关闭",
  "ai.prep.fault.oom": "第 2 批内存不足",
  "ai.prep.fault.crash": "第 2 批 Provider 崩溃",
  "ai.prep.fault.oomError": { zh: "模拟内存不足", note: "Error raised by the injected fault." },
  "ai.prep.fault.crashError": { zh: "模拟 Provider 崩溃", note: "Error raised by the injected fault." },
  "ai.prep.run": "开始 / 继续",
  "ai.prep.status": "读取状态",
  "ai.prep.clear": "清理假向量",
  "ai.prep.summary.indexeddb": "暂存 {staged} 块 / 已发布 {published} 块；恢复点 {next}。IndexedDB 版本 {schema}，mock 组件 {component}。已预留 {bytes} 字节。",
  "ai.prep.summary.sqlite": "暂存 {staged} 块 / 已发布 {published} 块；恢复点 {next}。SQLite {sqlite}，数据库版本 {schema}（支持至 {supported}），mock 组件 {component}，锁等待 {timeout} ms。已预留 {bytes} 字节。",

  "ai.sem.title": "单书语义检索（调试）",
  "ai.sem.region": { zh: "单书语义检索", note: "Accessible label of the section." },
  "ai.sem.note.preview": "浏览器预览：使用固定测试向量在 IndexedDB 中真实建库、恢复与排序，用于验证交互；这不是本机 Windows GPU 模型结果，也不代表已接入真实 Embedding。",
  "ai.sem.note.desktop": "桌面 AI 调试版：使用已验证的本机 ONNX Runtime DirectML 模型；查询与建库共享同一原生许可，阅读优先在批次边界让行。",
  "ai.sem.note.scope": "一次只处理当前书。不自动下载模型，不做问答、总结或跨书融合。",
  "ai.sem.note.scopePreview": "一次只处理当前书。不自动下载模型，不做问答、总结或跨书融合。需要真实语义检索时请在 Windows AI 调试版运行。",
  "ai.sem.initial": "尚未建库。语义索引只在点击“建立索引”后开始，不会自动下载模型或后台建库。",
  "ai.sem.rebuilding": "正在重建；不会复用旧的已发布代次。",
  "ai.sem.building": "正在建立语义索引；关闭面板会保留可恢复检查点。",
  "ai.sem.querying": "正在查询本地已发布代次…",
  "ai.sem.hits.one": "第 {generation} 代命中 {count} 段。cosine 得分只表示相似度排序，不是置信概率。",
  "ai.sem.hits.other": "第 {generation} 代命中 {count} 段。cosine 得分只表示相似度排序，不是置信概率。",
  "ai.sem.noHits": "没有命中任何段落。",
  "ai.sem.probing": "正在加载已验证模型并运行一次真实短句嵌入…",
  "ai.sem.probeReport": {
    zh: "设备 {adapter}（LUID {luid}，DirectML 索引 {index}）｜运行库 {runtime}｜token 查询/段落 {queryTokens}/{passageTokens}｜归一 {norm}，最大绝对值 {maxAbs}｜向量摘要 {digest}…｜耗时 {ms} ms｜query/passage cosine {cosine}",
    note: "One-line diagnostic report of the real model probe; keep the '|' separators.",
  },
  "ai.sem.probeFailed": "探针失败：{error}",
  "ai.sem.summary.state": "状态：{state}",
  "ai.sem.summary.model": "模型：{model}",
  "ai.sem.summary.device": "设备：{device}",
  "ai.sem.summary.generation": "已发布代次：{generation}",
  "ai.sem.summary.rows": "已发布段落：{rows}",
  "ai.sem.summary.staged": "暂存/恢复点：{staged} / 第 {batch} 批",
  "ai.sem.notOpened": "尚未打开",
  "ai.sem.browserStore": "浏览器 IndexedDB",
  "ai.sem.notProbed": "尚未探测",
  "ai.sem.none": "无",
  "ai.sem.build": "建立索引 / 继续",
  "ai.sem.clear": "清理本书语义索引",
  "ai.sem.cancelRequested": "已请求取消；driver 结束前会保留占用与恢复点。",
  "ai.sem.query": "查询",
  "ai.sem.queryPlaceholder": "用自然语言描述要查找的内容",
  "ai.sem.probe": "真实模型探针",
  "ai.sem.retry": "重试读取状态",
  "ai.sem.hit": { zh: "{chapter}（{score}）：{text}", note: "Search hit button: chapter title, similarity score, text excerpt." },
  "ai.sem.state.idle": "未检查",
  "ai.sem.state.checking": "检查中",
  "ai.sem.state.unavailable": "未接入/不可用",
  "ai.sem.state.building": "处理中",
  "ai.sem.state.ready": "已就绪",
  "ai.sem.state.failed": "失败",
});
