import { defineMessages } from "../defineMessages";

/** App frame pieces outside the panels: placeholders, the phone "more" sheet and progress-choice dialogs. */
export const appUi = defineMessages("appUi", {
  "appUi.appName": { zh: "EPUB 阅读器", note: "Window/top bar title on the shelf." },
  "appUi.showTools": "显示阅读工具",
  "appUi.preparingShelf": "正在准备书架…",
  "appUi.openingFile": { zh: "正在打开《{name}》…", note: "{name} is a file name." },
  "appUi.cannotOpen": "无法打开",
  "appUi.chooseAgain": "重新选择文件",
  "appUi.aiLoading": "正在加载 AI 开发面板…",
  "appUi.more.dialog": "更多阅读操作",
  "appUi.more.title": { zh: "更多", max: 10 },
  "appUi.more.ai": "AI 助手",
  "appUi.more.log": "诊断日志",
  "appUi.exitHint": { zh: "再滑一次退出阅读器", note: "Android back gesture: swipe once more to leave the reader." },
  "appUi.checkpoint.dialog": "选择未确认阅读位置",
  "appUi.checkpoint.title": "选择阅读位置",
  "appUi.checkpoint.body": "《{title}》有一处本机未确认位置，且原显示版本已失效{synced}。请选择本次打开方式。",
  "appUi.checkpoint.syncedAvailable": { zh: "；同步位置也可用", note: "Inserted into checkpoint.body; starts with a clause separator." },
  "appUi.checkpoint.useLocal": "使用本机未确认位置",
  "appUi.checkpoint.useSynced": "使用同步位置",
  "appUi.cancel": { zh: "取消", max: 10 },
  "appUi.progressChoice.dialog": "选择恢复进度",
  "appUi.progressChoice.title": "选择恢复进度",
  "appUi.progressChoice.body.other": "《{title}》有 {count} 个阅读进度版本，请选择要恢复的一项。",
  "appUi.progressChoice.body.one": { zh: "《{title}》有 {count} 个阅读进度版本，请选择要恢复的一项。", note: "Singular form." },
  "appUi.chapterN": "第 {n} 章",
  "appUi.runtime.ai": { zh: "AI 地基：{message}", note: "Diagnostic log line prefix for the AI foundation." },
  "appUi.issue.noteSaveFailed": "笔记保存失败：{error}",
  "appUi.issue.selectionGone": "选区已失效，无法保存笔记",
  "appUi.issue.noteVersionMissing": "笔记展示版本信息缺失，已取消编辑以避免覆盖后台更新",
  "appUi.issue.noteEditFailed": "无法打开笔记编辑：{error}",
  "appUi.issue.noteChapterGone": "笔记对应的章节已不存在",
  "appUi.issue.linkFailed": "打开外部链接失败：{error}",
  "appUi.issue.fullscreenFailed": "全屏切换失败：{error}",
  "appUi.issue.windowFullscreenFailed": "窗口全屏切换失败：{error}",
  "appUi.issue.copyFailed": "复制失败：{error}",
  "appUi.issue.copyOriginalFailed": "复制原文失败：{error}",
});
