import { defineMessages } from "../defineMessages";

/** Shelf → Cache & storage panel (index cache size, directory and reset). */
export const cache = defineMessages("cache", {
  "cache.state.building": "正在建立",
  "cache.state.ready": "可用",
  "cache.state.partial": "部分可用",
  "cache.state.error": "异常",
  "cache.state.empty": "空",
  "cache.indexedBooks": { zh: "已索引书籍", note: "Followed by a bold number." },
  "cache.state": { zh: "状态", note: "Followed by a bold state." },
  "cache.updated": { zh: "最近更新", note: "Followed by a date/time." },
  "cache.size": { zh: "分类占用", note: "Followed by a size like 12 MB." },
  "cache.chooseDirectory.title": "选择缓存目录",
  "cache.saved": "已保存；本次仍使用原目录，下次启动生效。",
  "cache.restored": "已恢复默认；本次仍使用原目录，下次启动生效。",
  "cache.cleared": "全文索引已清除，空闲缓存空间已回收；全文搜索需要重新准备。",
  "cache.reset.done": "全部索引缓存已重置；书本、进度和模型资料已保留，搜索需要重新准备。",
  "cache.dialog": "缓存与存储",
  "cache.title": "缓存与存储",
  "cache.deviceOnly": "设置只用于当前设备。",
  "cache.close.label": "关闭缓存与存储",
  "cache.close": { zh: "关闭", max: 8 },
  "cache.fallback": { zh: "自定义目录不可用，已回退到默认目录：{reason}", note: "{reason} is a technical detail." },
  "cache.loading": "正在读取缓存状态…",
  "cache.reset.hint": "索引数据库损坏或无法清理时，可重置全部索引缓存。书本、阅读进度和模型资料保留。",
  "cache.resetting": "正在重置…",
  "cache.reset": "重置全部索引缓存",
  "cache.activeDirectory": "本次使用目录",
  "cache.savedDirectory": "已保存目录",
  "cache.defaultDirectory": "默认目录",
  "cache.defaultDirectory.detail": "默认（应用数据目录）",
  "cache.restartRequired": "设置已保存，重启应用后生效。",
  "cache.choosing": "正在选择…",
  "cache.chooseDirectory": "选择缓存目录",
  "cache.restoring": "正在恢复…",
  "cache.restoreDefault": "恢复默认",
  "cache.total": "索引缓存数据库总占用",
  "cache.fullText": "全文索引",
  "cache.clear.building": "正在建立全文索引，完成后才能清理",
  "cache.clear": "清除全文索引",
  "cache.clearing": "正在清除…",
  "cache.fullText.none": "暂无全文索引分类。",
  "cache.clear.hint": "清除后全文搜索需要重新准备；清除时会整理数据库并回收空闲空间。",
});
