import { defineMessages } from "../defineMessages";

/**
 * Reader "字符与画面" sub-page: character display (Chinese script conversion
 * and replacement rules), visual filters and colour-weakness assistance.
 */
export const display = defineMessages("display", {
  "display.dialog": "字符与画面设置",
  "display.back.tip": "返回排版与外观",
  "display.back": "返回",
  "display.title": { zh: "字符与画面", max: 16 },
  "display.close.tip": "关闭设置 (Esc)",
  "display.close": "关闭",

  "display.text.section": "字符替换与繁简显示",
  "display.text.title": "字符显示",
  "display.text.note": "只改变阅读显示，不修改原书；先繁简转换，再套用下方规则。",
  "display.text.script": { zh: "繁简", note: "Row label: Simplified/Traditional Chinese conversion.", max: 10 },
  "display.text.mode": "显示模式",
  "display.text.mode.original": { zh: "原文", note: "Show the book's own script.", max: 8 },
  "display.text.mode.simplified": { zh: "简体", note: "Convert to Simplified Chinese.", max: 8 },
  "display.text.mode.traditional": { zh: "繁体", note: "Convert to Traditional Chinese.", max: 8 },
  "display.text.rules": "自定义规则",
  "display.text.rules.order": "最长原文优先，同长按列表顺序",
  "display.text.rules.add": { zh: "添加", max: 8 },
  "display.text.rules.empty": "暂未添加规则",
  "display.text.rule.from": { zh: "规则 {n} 原文", note: "Accessible label of rule n's 'find' field." },
  "display.text.rule.fromPlaceholder": { zh: "原文", note: "Placeholder: text to find.", max: 10 },
  "display.text.rule.to": { zh: "规则 {n} 显示", note: "Accessible label of rule n's 'show as' field." },
  "display.text.rule.toPlaceholder": { zh: "显示为", note: "Placeholder: replacement shown instead.", max: 10 },
  "display.text.rule.disable": "停用此规则",
  "display.text.rule.enable": "启用此规则",
  "display.text.rule.enableN": "启用规则 {n}",
  "display.text.rule.on": { zh: "启用", max: 8 },
  "display.text.rule.off": { zh: "停用", max: 8 },
  "display.text.rule.up": "上移",
  "display.text.rule.down": "下移",
  "display.text.rule.remove": "删除",
  "display.text.rule.duplicate": "原文重复：采用列表中第一条，此条不会生效。",
  "display.text.preview": { zh: "预览", max: 8 },
  "display.text.previewResult": { zh: "显示", max: 8 },
  "display.text.previewBusy": "转换中…",
  "display.text.previewFailed": "预览失败",
  "display.text.restore": "恢复原文",

  "display.visual.section": "画面滤镜",
  "display.visual.title": "画面滤镜",
  "display.visual.enable": "启用滤镜",
  "display.visual.enable.note": "总开关，同时控制色弱辅助；不重排章节",
  "display.visual.enable.label": "启用画面滤镜",
  "display.visual.invert": "反色",
  "display.visual.invert.label": "反色/反相",
  "display.visual.grayscale": "灰度",
  "display.visual.saturation": "饱和度",
  "display.visual.sharpen": "锐化",
  "display.visual.dim": "暗化",
  "display.visual.reset": "恢复默认",
  "display.visual.compare.tip": "按住临时查看原画面，松开恢复滤镜",
  "display.visual.compare": "按住查看原画面",

  "display.assist.off": { zh: "关闭", max: 14 },
  "display.assist.off.detail": "不改变画面",
  "display.assist.protan": "红色弱／红色盲辅助",
  "display.assist.deutan": "绿色弱／绿色盲辅助",
  "display.assist.tritan": "蓝色弱／蓝色盲辅助",
  "display.assist.swatch.red": "红",
  "display.assist.swatch.yellow": "黄",
  "display.assist.swatch.green": "绿",
  "display.assist.swatch.cyan": "青",
  "display.assist.swatch.blue": "蓝",
  "display.assist.swatch.magenta": "洋红",
  "display.assist.section": "色弱辅助",
  "display.assist.title": "色弱辅助",
  "display.assist.note": { zh: "把易混的色差移到更好分辨的颜色方向；只改变显示，不宣称修复视力。", note: "Must not claim to fix eyesight." },
  "display.assist.kind": "辅助类型",
  "display.assist.strength": { zh: "强度", max: 10 },
  "display.assist.strength.label": "色弱辅助强度",
  "display.assist.preview": { zh: "同屏预览：上排原色，下排{mode}辅助后", note: "{mode} is the selected assistance name." },
  "display.assist.original": { zh: "原色", max: 10 },
  "display.assist.after": { zh: "辅助后", max: 10 },
  "display.assist.swatchOriginal": { zh: "{color} 原色", note: "Tooltip on an original colour swatch." },
  "display.assist.swatchAfter": { zh: "{color} {mode}辅助后", note: "Tooltip on an adjusted swatch." },
  "display.assist.grayscaleNote": "同时开启灰度时，色差会被抹去，辅助效果随之减弱。",
});
