import { defineMessages } from "../defineMessages";

/**
 * Import-a-folder dialog: scan a system folder for EPUBs and file them into
 * shelf folders. Folder and file names inside 「」 are user data, never translated.
 */
export const folderImport = defineMessages("folderImport", {
  "folderImport.phase.scanning": "正在扫描",
  "folderImport.phase.preparing": "正在读取书籍",
  "folderImport.phase.committing": "正在保存当前批次",
  "folderImport.phase.cleaning": "正在清理",
  "folderImport.target.existing.other": { zh: "放入已有「{name}」（{count} 本）", note: "Dropdown option; {name} is an existing shelf folder." },
  "folderImport.target.existing.one": { zh: "放入已有「{name}」（{count} 本）", note: "Singular form." },
  "folderImport.scanFailed": { zh: "扫描失败：{error}", note: "{error} is a technical detail." },
  "folderImport.importFailed": { zh: "导入失败：{error}。已完成的书仍保留在书架。", note: "{error} is a technical detail." },
  "folderImport.dialog": "导入文件夹",
  "folderImport.title": "导入文件夹",
  "folderImport.subtitle": "选择一个系统文件夹，自动找出其中的 EPUB，并按目录整理到书架文件夹。只读取，不改动原文件。",
  "folderImport.unsupported": { zh: "当前环境不支持选择文件夹。可以用「导入图书」一次多选文件，但不会保留目录关系。", note: "「导入图书」 must match the shelf import button (shelf.import.books)." },
  "folderImport.intro": "扫描只读取文件名和目录，不读正文；确认一次后开始导入，可随时停止，已完成的书会保留。",
  "folderImport.scanning": "正在扫描文件夹…",
  "folderImport.scanning.found.other": "正在扫描文件夹…已发现 {count} 本",
  "folderImport.scanning.found.one": { zh: "正在扫描文件夹…已发现 {count} 本", note: "Singular form." },
  "folderImport.listing": "正在整理清单 {loaded} / {total}",
  "folderImport.empty": { zh: "「{name}」中未找到 EPUB。", note: "{name} is the chosen folder name." },
  "folderImport.candidates": "EPUB 候选",
  "folderImport.candidates.count.other": { zh: "{count} 本", max: 12 },
  "folderImport.candidates.count.one": { zh: "{count} 本", note: "Singular form.", max: 12 },
  "folderImport.shelfFolders": "书架文件夹",
  "folderImport.shelfFolders.count.other": { zh: "{count} 个", max: 12 },
  "folderImport.shelfFolders.count.one": { zh: "{count} 个", note: "Singular form.", max: 12 },
  "folderImport.flattened": { zh: "深层目录已展开：书架只保留一层，文件夹名带上级目录，例如「分类 · 子分类」。", note: "Example folder name in 「」 may be translated." },
  "folderImport.grouping": "整理方式",
  "folderImport.grouping.auto": "按目录整理",
  "folderImport.grouping.auto.hint": "每个目录对应一个书架文件夹",
  "folderImport.grouping.single": "统一放入「{name}」",
  "folderImport.grouping.single.hint": "所有书放进一个同名文件夹",
  "folderImport.grouping.none": "不自动分类",
  "folderImport.grouping.none.hint": "只导入书籍，不创建文件夹",
  "folderImport.loose": { zh: "「{name}」直属的书", note: "Books directly inside the chosen folder (not in a subfolder)." },
  "folderImport.loose.unclassified": "留在未分类",
  "folderImport.loose.namedFolder": "放入「{name}」文件夹",
  "folderImport.existing": "书架里已有的书",
  "folderImport.existing.fill": "只整理未分类的已有书",
  "folderImport.existing.fill.hint": "已在文件夹里的书保持不动（推荐）",
  "folderImport.existing.preserve": "保留已有归属",
  "folderImport.existing.preserve.hint": "已有的书一律不移动",
  "folderImport.existing.replace": "按此次目录调整",
  "folderImport.existing.replace.hint": "已有的书也按目录移动",
  "folderImport.folders": "文件夹",
  "folderImport.looseCount.other": "另有 {count} 本留在未分类",
  "folderImport.looseCount.one": { zh: "另有 {count} 本留在未分类", note: "Singular form." },
  "folderImport.unresolved.other": "有 {count} 个文件夹与书架上多个同名文件夹对应，请为它们选择目标。",
  "folderImport.unresolved.one": { zh: "有 {count} 个文件夹与书架上多个同名文件夹对应，请为它们选择目标。", note: "Singular form." },
  "folderImport.groupPath.other": { zh: "{path} · {count} 本", note: "{path} is 'Folder / Sub'." },
  "folderImport.groupPath.one": { zh: "{path} · {count} 本", note: "Singular form." },
  "folderImport.groupTarget": { zh: "{name} 的目标文件夹", note: "Accessible label of the target dropdown." },
  "folderImport.choose": "请选择…",
  "folderImport.create": "新建「{name}」",
  "folderImport.createSameName": "新建同名「{name}」",
  "folderImport.showMore": "显示更多（还有 {count} 个）",
  "folderImport.duplicatesNote": "书数为候选数量；重复的书会在导入时按内容识别，进度、笔记、书签和收藏都会保留。",
  "folderImport.settling": "正在完成当前批次，之后停止。已完成的书会保留。",
  "folderImport.stopping": "正在停止，已完成的书会保留。",
  "folderImport.done.cancelled": "已停止导入，已完成的书保留在书架。",
  "folderImport.done.failed": "导入未全部完成，已完成的书保留在书架。",
  "folderImport.done.ok": "导入完成。",
  "folderImport.result.imported": { zh: "新增", max: 10 },
  "folderImport.result.duplicates": { zh: "重复", max: 10 },
  "folderImport.result.failed": { zh: "失败", max: 10 },
  "folderImport.result.unplaced": { zh: "未归档", note: "Imported but not filed into a folder.", max: 10 },
  "folderImport.result.createdFolders": { zh: "新建文件夹", max: 14 },
  "folderImport.result.completed": { zh: "已处理", max: 10 },
  "folderImport.issues": "查看问题（{count}）",
  "folderImport.loading": "正在加载…",
  "folderImport.loadMore": "加载更多",
  "folderImport.stop": { zh: "停止导入", max: 12 },
  "folderImport.cancel": { zh: "取消", max: 10 },
  "folderImport.rechoose": { zh: "重新选择", max: 12 },
  "folderImport.start": { zh: "开始导入", max: 12 },
  "folderImport.done": { zh: "完成", max: 10 },
  "folderImport.close": { zh: "关闭", max: 10 },
  "folderImport.useFiles": { zh: "多选文件导入", max: 16 },
  "folderImport.chooseFolder": { zh: "选择文件夹", max: 14 },
  "folderImport.unreadable": "{count} 个目录无法读取，预览只包含已访问的部分。",
  "folderImport.skippedLinks": "已跳过 {count} 个链接目录。",
  "folderImport.preparing": "正在准备…",
  "folderImport.progress.of": { zh: " · {completed} / {total}", note: "Appended to the phase label." },
  "folderImport.progress.processed": { zh: " · 已处理 {completed}", note: "Appended to the phase label." },
  "folderImport.progress.counts": { zh: "新增 {imported} · 重复 {duplicates} · 失败 {failed}", note: "Running totals." },
  "folderImport.progress.unplaced": { zh: " · 未归档 {count}", note: "Appended to the running totals." },
  "folderImport.issue.folderDeleted": "目标文件夹已被删除，书已导入但未归档",
  "folderImport.issue.categoryChanged": "导入期间这本书的分类发生变化，已保留新的分类",
  "folderImport.issue.placementFailed": { zh: "书已导入，归档失败：{error}", note: "{error} is a technical detail." },
  "folderImport.issue.sourceGone": "源文件已不可用",
  "folderImport.issue.multipleSources": { zh: "同一本书在多个目录出现，已采用排在前面的来源（{file}）", note: "{file} is a file name." },
  "folderImport.issue.sourceFailed": { zh: "{file}：{error}", note: "File name and a technical detail." },
  "folderImport.issue.stopped": "已停止导入，书已导入但未归档",
});
