import { defineMessages } from "../defineMessages";

/**
 * Device transfer (设备互传): QR pairing over the same Wi‑Fi. Errors are
 * written for the user from stable codes; native technical text is not shown.
 */
export const lan = defineMessages("lan", {
  "lan.error.unreachable": "连不上对方设备。请确认两台设备连着同一个 Wi‑Fi。公司、学校或酒店的网络可能不允许设备互连，可以改用手机热点。",
  "lan.error.expired": "二维码已失效。请在对方设备上重新显示二维码，再扫一次。",
  "lan.error.invalidLink": "这不是有效的连接信息。请重新扫码，或复制完整的连接信息再粘贴。",
  "lan.error.invalidData": "传输的数据不完整。请重新连接后再试一次。",
  "lan.error.busy": "另一项导入或导出正在进行，请等它完成后再试。",
  "lan.error.network": "网络连接中断了。请确认两台设备都还连着同一个 Wi‑Fi，然后重新连接。",
  "lan.error.secure": "没能建立安全连接。请在对方设备上重新显示二维码后再试。",
  "lan.error.readBooks": "读取要发送的书籍时出错。请确认书籍文件还在原来的位置。",
  "lan.error.save": "保存时出错。请确认设备存储空间充足。",
  "lan.error.spaceSend": "空间不足，无法准备这次发送。请释放空间，或少选一些书。",
  "lan.error.spaceReceive": "空间不足，无法接收这次传输。请释放空间后重新连接，或让对方少选一些书。",
  "lan.error.metadataTooLarge": "这次阅读资料太多。请少选一些书，分批发送。",
  "lan.error.protocol": "两台设备需要更新到支持同一互传协议的版本。",
  "lan.error.ended": "连接已经结束了。请重新连接。",
  "lan.error.cancelled": "已取消。",
  "lan.error.unsupported": "这台设备暂不支持设备互传。",
  "lan.error.generic": "这次传输没有完成。请重新连接后再试一次。",
  "lan.scan.permission": { zh: "需要相机权限才能扫码。可以在系统设置里允许使用相机，或改用「粘贴连接信息」。", note: "「…」 quotes the name of a button; keep it matching 'lan.paste'." },
  "lan.scan.noCamera": "这台设备没有可用的相机，请改用「粘贴连接信息」。",
  "lan.scan.cameraError": "相机暂时无法使用，可能正被其他应用占用。请稍后再试，或改用「粘贴连接信息」。",
  "lan.scan.failed": "无法打开扫码，请改用「粘贴连接信息」。",
  "lan.phase.preparing": "正在准备",
  "lan.phase.reading": "正在读取",
  "lan.phase.extracting": "正在解压",
  "lan.phase.writing": "正在写入",
  "lan.phase.finalizing": "即将完成",
  "lan.phase.copying": "正在传输",
  "lan.phase.committing": "正在写入书架",
  "lan.phase.receiving": "正在接收",
  "lan.phase.working": "正在处理",
  "lan.progress.bytes": { zh: "{done} / {total}", note: "Sizes like '3.2 MB'." },
  "lan.progress.processed": "已处理 {done}",
  "lan.offer.books.other": { zh: "对方想发送 {count} 本书的资料", note: "Incoming transfer: reading data for N books." },
  "lan.offer.books.one": { zh: "对方想发送 {count} 本书的资料", note: "Singular form." },
  "lan.offer.settings": "对方想发送阅读设置",
  "lan.offer.dataOnly": { zh: "只包含阅读进度、书签和笔记，共 {size}。", note: "{size} like '120 KB'." },
  "lan.offer.summary": { zh: "同步 {count} 本资料，{attached}{reused}{skipped}。", note: "Sentence assembled from the next three parts; {reused}/{skipped} may be empty." },
  "lan.offer.attached": "新传 {count} 本书",
  "lan.offer.reused": { zh: "，你已有 {count} 本书", note: "Starts with a comma; appended to the summary." },
  "lan.offer.skipped": { zh: "；另有 {count} 本书没有可用文件，只同步资料", note: "Starts with a semicolon; appended to the summary." },
  "lan.notice.committing": "提交已经开始，关闭窗口不会回滚。",
  "lan.notice.connected": "已连接：可以发送资料，也可以等待对端发送。",
  "lan.notice.endedWaiting": "连接已结束，正在等待本机结果。",
  "lan.notice.ended": "连接已结束，请重新连接。",
  "lan.notice.failed": "设备互传失败。",
  "lan.notice.pasteFirst": "请先粘贴完整的连接信息。",
  "lan.notice.sendFailed": "发送失败。",
  "lan.notice.peerImported": "对方已导入。",
  "lan.notice.peerUnconfirmed": "连接已结束，对方导入结果未确认。",
  "lan.notice.sendCancelled": "已取消发送。",
  "lan.notice.imported.other": "已导入 {count} 本资料。",
  "lan.notice.imported.one": { zh: "已导入 {count} 本资料。", note: "Singular form." },
});
