import { defineMessages } from "../defineMessages";

/** Device transfer panel UI. Bottom sheet on phones; tiles and buttons are narrow. */
export const lanPanel = defineMessages("lanPanel", {
  "lanPanel.copyFailed": "没能复制到剪贴板，请再试一次。",
  "lanPanel.sourceLabel": { zh: "设备互传", note: "Source name shown in the import preview." },
  "lanPanel.openSettings": "打开系统设置",
  "lanPanel.intro": "两台设备连同一个 Wi‑Fi，一台显示二维码，另一台扫码，就能互传书籍和阅读进度。",
  "lanPanel.host": { zh: "显示二维码", max: 16 },
  "lanPanel.host.detail": { zh: "让另一台设备来扫", max: 22 },
  "lanPanel.scanOpening": { zh: "正在打开相机…", max: 16 },
  "lanPanel.scan": { zh: "扫码连接", max: 16 },
  "lanPanel.scan.detail": { zh: "扫另一台设备的二维码", max: 22 },
  "lanPanel.paste.android": { zh: "不方便扫码？粘贴连接信息", note: "Row button on phones." },
  "lanPanel.paste": "粘贴另一台设备的连接信息",
  "lanPanel.pairingInfo": "连接信息",
  "lanPanel.paste.placeholder": "粘贴另一台设备复制的连接信息",
  "lanPanel.connect": { zh: "连接", max: 10 },
  "lanPanel.help": "连不上怎么办",
  "lanPanel.help.sameWifi": "确认两台设备连着同一个 Wi‑Fi，或者都连同一部手机的热点。",
  "lanPanel.help.guestNetwork": "公司、学校、酒店的网络和路由器的“访客网络”常常禁止设备互连，可以改用手机热点。",
  "lanPanel.help.firewall": "电脑上如果弹出防火墙提示，请选择允许。",
  "lanPanel.network": "选择要使用的网络",
  "lanPanel.bindIp": "高级：指定本机网络地址（一般不需要填写）",
  "lanPanel.bindIp.placeholder": { zh: "例如 192.168.1.10", note: "Keep the example address." },
  "lanPanel.qr": "设备互传二维码",
  "lanPanel.qrFailed": "二维码显示失败，请点下方「复制连接信息」，在另一台设备粘贴。",
  "lanPanel.scanThis": "用另一台设备扫描这个二维码",
  "lanPanel.step.open": { zh: "在另一台设备打开「书架设置 → 设备互传」", note: "Names in 「」 must match the shelf menu and this panel's title." },
  "lanPanel.step.scan": "选择「扫码连接」，对准这个二维码",
  "lanPanel.waiting": "等待连接…",
  "lanPanel.copied": { zh: "已复制", max: 14 },
  "lanPanel.copy": { zh: "复制连接信息", max: 14 },
  "lanPanel.cancel": { zh: "取消", max: 10 },
  "lanPanel.send.region": "发送给对方",
  "lanPanel.send.what": "发送什么",
  "lanPanel.send.scope": "发送范围",
  "lanPanel.send.all": { zh: "全部书籍", max: 14 },
  "lanPanel.send.selected.other": { zh: "已选 {count} 本", max: 14 },
  "lanPanel.send.selected.one": { zh: "已选 {count} 本", note: "Singular form.", max: 14 },
  "lanPanel.send.selectedNone": { zh: "已选的书", max: 14 },
  "lanPanel.send.selectHint": "只想发几本？先在书架用「批量选择」选好，再点「发到设备」。",
  "lanPanel.send.includeBooks": "附带书籍文件",
  "lanPanel.send.includeBooks.on": "对方可以直接打开阅读，书多时要多等一会",
  "lanPanel.send.includeBooks.off": "只发阅读资料，对方需要已有这些书",
  "lanPanel.send.note": "总会带上阅读资料：进度、书签、笔记、收藏和文件夹。全部书籍含空文件夹，已选的书只带相关文件夹。",
  "lanPanel.send": { zh: "发送", max: 10 },
  "lanPanel.waitPeer": "也可以等对方发给你",
  "lanPanel.offer.hint": "接收后会先显示导入预览，确认后才会写入书架。",
  "lanPanel.accept": { zh: "接收", max: 10 },
  "lanPanel.decline": { zh: "拒绝", max: 10 },
  "lanPanel.progress.sending": "正在发送",
  "lanPanel.progress.receiving": "正在接收",
  "lanPanel.progress.checking": "正在检查收到的资料",
  "lanPanel.progress.writing": "正在写入书架",
  "lanPanel.progress.percent": { zh: "{label} {percent}%", note: "Phase label followed by a percentage." },
  "lanPanel.progress.committing": "马上就好。现在关闭面板也不会中断，完成后书架会自动更新。",
  "lanPanel.done": { zh: "完成", max: 10 },
  "lanPanel.again": { zh: "再传一次", max: 12 },
  "lanPanel.reconnect": { zh: "重新连接", max: 12 },
  "lanPanel.close": { zh: "关闭", max: 10 },
  "lanPanel.skipped.other": "有 {count} 本书的文件没有找到，只发送了它们的阅读进度。",
  "lanPanel.skipped.one": { zh: "有 {count} 本书的文件没有找到，只发送了它们的阅读进度。", note: "Singular form." },
  "lanPanel.sent.title": "发送完成",
  "lanPanel.sent.imported.other": "对方已导入 {count} 本书。",
  "lanPanel.sent.imported.one": { zh: "对方已导入 {count} 本书。", note: "Singular form." },
  "lanPanel.sent.received": "对方已收到并导入。",
  "lanPanel.unconfirmed.title": "已发送，但没收到对方确认",
  "lanPanel.unconfirmed.detail": "连接在对方确认前断开了。请在对方设备的书架上看看这些书是否已经导入。",
  "lanPanel.notSent.title": "发送没有完成",
  "lanPanel.notSent.detail": "发送被取消，或者对方没有接收。对方的书架没有任何变化。",
  "lanPanel.failed.title": "发送失败",
  "lanPanel.connecting": "正在连接…",
  "lanPanel.imported.title": "导入完成",
  "lanPanel.imported.books.other": "已导入 {count} 本书，书架已经更新。",
  "lanPanel.imported.books.one": { zh: "已导入 {count} 本书，书架已经更新。", note: "Singular form." },
  "lanPanel.imported.data": "资料已导入，书架已经更新。",
  "lanPanel.closed.title": "连接已断开",
  "lanPanel.closed.detail": "对方已经断开连接。需要继续传送时，请重新连接。",
  "lanPanel.subtitle.idle": "同一 Wi‑Fi 下直接传送，不经过云端",
  "lanPanel.subtitle.host": "等待另一台设备扫码",
  "lanPanel.subtitle.active": "请保持两台设备都打开本应用",
  "lanPanel.title": { zh: "设备互传", max: 16 },
  "lanPanel.connected": "已连接另一台设备",
  "lanPanel.disconnect": { zh: "断开", max: 10 },
  "lanPanel.close.label": "关闭设备互传",
  "lanPanel.dialog": "设备互传",
});
