import { defineMessages } from "../defineMessages";

/**
 * App-level notices shown as a banner on the shelf or a toast in the reader.
 * {error}/{detail} carry raw technical text that stays untranslated. Compound
 * notices are joined with "notice.sep".
 */
export const notice = defineMessages("notice", {
  "notice.sep": { zh: "；", note: "Joins clauses of one notice, e.g. '; ' in English." },
  "notice.listSep": { zh: "、", note: "Separator between list items, e.g. ', '." },
  "notice.selectedFile": { zh: "选中文件", note: "Fallback name of a picked file." },
  "notice.nthBook": { zh: "第 {n} 本", note: "Fallback name for the n-th picked file." },
  "notice.statusBar.saveFailed": "系统状态栏设置保存失败：{error}",
  "notice.statusBar.failed": "系统状态栏调整失败：{error}",
  "notice.keepScreenOn.saveFailed": "屏幕常亮设置保存失败：{error}",
  "notice.keepScreenOn.failed": "屏幕常亮设置失败：{error}",
  "notice.busy": "正在处理…",
  "notice.discardNote": "放弃未保存的笔记？",
  "notice.import.busy": "已有导入任务正在进行，请等待当前任务结束",
  "notice.import.running": "正在导入书籍…",
  "notice.import.itemFailed": { zh: "{name}：{error}", note: "A file name and the reason it failed." },
  "notice.import.failedShort": "导入失败",
  "notice.import.noRecord": "后端未返回书架记录",
  "notice.import.oldVersionKept": "书架仍有源文件不可用的旧书，原进度和笔记已保留；内容不同的文件作为另一版本导入",
  "notice.import.refreshFailed": "导入已完成，但书架刷新失败：{error}",
  "notice.import.failed": "导入失败：{error}",
  "notice.import.oneEpub": { zh: "1 本 EPUB", max: 16 },
  "notice.import.files.other": { zh: "{count} 个文件", max: 16 },
  "notice.import.files.one": { zh: "{count} 个文件", note: "Singular form.", max: 16 },
  "notice.import.cancelledCount.other": "已取消 {count} 本",
  "notice.import.cancelledCount.one": { zh: "已取消 {count} 本", note: "Singular form." },
  "notice.import.cancelFailed": "取消导入失败：{error}",
  "notice.reimport.title": { zh: "重新导入《{title}》", note: "System file picker title." },
  "notice.reimport.cancelled": "《{title}》重新导入已取消",
  "notice.reimport.mismatch": "选择的文件与《{title}》内容不一致，无法恢复",
  "notice.picker.chooseEpub": { zh: "选择 EPUB 书籍", note: "System file picker title." },
  "notice.picker.epubFilter": { zh: "EPUB 电子书", note: "File type name in the system picker." },
  "notice.picker.failed": "无法打开文件选择器：{error}",
  "notice.organization.readFailedLocked": "收藏与文件夹读取失败，已禁用修改以防止覆盖现有数据",
  "notice.operationFailed": "操作失败：{error}",
  "notice.folderImport.blocked": "存档或设备互传进行中，暂不能导入文件夹",
  "notice.folderImport.openFailed": "无法打开文件夹导入：{error}",
  "notice.shelf.refreshFailed": "书架刷新失败：{error}",
  "notice.shelf.refreshFailedShort": { zh: "书架刷新失败", note: "A clause appended to a summary notice." },
  "notice.archive.exportTitle": { zh: "导出存档", note: "System save dialog title." },
  "notice.archive.importTitle": { zh: "导入存档", note: "System open dialog title." },
  "notice.archive.filter": { zh: "EPUB Reader 存档", note: "File type name in the system picker; keep the product name." },
  "notice.archive.androidDocument": "Android 文档",
  "notice.archive.rangeSelected.other": "选中的 {count} 本资料",
  "notice.archive.rangeSelected.one": { zh: "选中的 {count} 本资料", note: "Singular form." },
  "notice.archive.rangeAll": "全库资料",
  "notice.archive.busy": "已有存档或互传任务正在进行，请等待当前任务结束",
  "notice.archive.savePickerFailed": "无法打开保存位置选择器：{error}",
  "notice.archive.exportCancelled": "已取消导出存档",
  "notice.archive.exportedSkipped": { zh: "已导出{range}；附带书籍 {written} 本，跳过 {skipped} 本（如《{title}》：{reason}）", note: "{range} is e.g. 'all library data'." },
  "notice.archive.exportedWithBooks": "已导出{range}，附带书籍 {written} 本",
  "notice.archive.exportedNoBooks": "已导出{range}（未附带书籍文件）",
  "notice.archive.exportFailed": "存档导出失败：{error}",
  "notice.archive.openPickerFailed": "无法打开存档选择器：{error}",
  "notice.archive.importCancelled": "已取消导入存档",
  "notice.archive.prepareFailed": "存档导入准备失败：{error}",
  "notice.archive.committedRefreshFailed": "存档已提交，但刷新书架失败：{error}",
  "notice.archive.preferencesReadFailed": "书籍资料已导入，但外观设置读取失败：{error}",
  "notice.archive.conflicts": { zh: "{count} 本有进度分歧，打开时可选择", note: "A clause appended to the import summary." },
  "notice.archive.preferencesNotApplied": "存档外观设置未应用，本机设置保持不变",
  "notice.archive.preferencesApplied": "已应用存档中的外观设置",
  "notice.archive.imported": { zh: "已导入 {imported} 本资料；{missing} 本待补书籍", note: "Archive import summary; more clauses may follow." },
  "notice.archive.importFailed": "存档导入失败：{error}",
  "notice.archive.cancelFailed": "取消存档任务失败：{error}",
  "notice.archive.savingOrganization": "正在保存分类修改，请稍后再试",
  "notice.legacy.exportTitle": { zh: "导出阅读存档", note: "System save dialog title (old JSON format)." },
  "notice.legacy.exported": "已导出 {count} 本书及分类组织存档",
  "notice.legacy.importBlocked": "正在导入书籍，暂不能替换书库记录",
  "notice.legacy.importing": "正在导入存档…",
  "notice.legacy.importTitle": { zh: "导入阅读存档", note: "System open dialog title (old JSON format)." },
  "notice.legacy.tooLarge": "存档文件超过 16 MiB，已拒绝读取",
  "notice.legacy.imported": "已导入 {count} 本书的记录与分类",
  "notice.legacy.relocate": "{count} 本需重新定位源文件",
  "notice.legacy.preferencesNotApplied": "旧版 JSON 中的外观设置未自动应用",
  "notice.archiveFile.busy": "已有存档文件任务正在进行，请等待当前任务结束",
  "notice.portable.inactive": "跨平台资料未激活，继续使用旧模式：{error}",
  "notice.shelf.readFailed": "无法读取书架：{error}",
  "notice.organization.readFailed": "无法读取收藏与文件夹：{error}",
  "notice.organization.readFailedWrites": "无法读取收藏与文件夹：{error}；已禁用分类写入以保护现有数据",
  "notice.font.busy": "正在导入字体，请稍候",
  "notice.font.importedIgnored": "已导入 {imported} 个字体；忽略 {ignored} 个非字体文件",
  "notice.font.ignoredOnly": "已忽略 {ignored} 个非字体文件，仅支持 TTF/OTF/WOFF/WOFF2",
  "notice.font.deleteFailed": "字体删除失败：{error}",
  "notice.font.dropHere": "请打开字体设置后拖入字体",
  "notice.font.dropUnsupported": "字体面板仅支持 TTF/OTF/WOFF/WOFF2 字体文件",
  "notice.font.dropUnavailable": "拖放不可用，可用导入按钮重试",
  "notice.font.failed": "字体导入失败：{error}",
  "notice.font.importedOne": "已导入字体：{family}",
  "notice.font.imported.other": "已导入 {count} 个字体",
  "notice.font.imported.one": { zh: "已导入 {count} 个字体", note: "Singular form." },
  "notice.font.nativeUnsupported": "当前环境不支持原生字体路径导入",
  "notice.font.noneSupported": "未发现支持的字体文件，仅支持 TTF/OTF/WOFF/WOFF2",
  "notice.reader.positionNotFound": "未能定位保存位置，已停留在章节开头",
  "notice.reader.positionNotFoundKept": "未能定位保存位置，已停留在章节开头；原阅读进度已保留",
  "notice.reader.sourceNotFoundNote": "未能定位原文，请重新搜索或检查笔记",
  "notice.reader.paragraphOnly": "已定位结果段落，未能标出精确匹配",
  "notice.reader.noHighlight": "当前内核不支持正文高亮；已定位原文",
  "notice.reader.sourceNotFound": "未能定位原文，请重新搜索",
  "notice.reader.progressNotFound": "未能定位到指定进度",
  "notice.reader.noteAnchorNotFound": "未能定位笔记原文，请检查笔记锚点",
  "notice.open.opening": "正在打开书籍…",
  "notice.open.checkpointReadFailed": "本机未确认阅读位置读取失败：{error}",
  "notice.open.syncedPosition": "已按同步位置打开；本机未确认阅读位置仍保留，待实际写入成功后确认。",
  "notice.open.versionGone": "所选进度版本已失效，请重新打开",
  "notice.open.previousUnsaved": "上一本书进度未保存，已保留到下次重试；本次继续打开当前书。",
  "notice.open.relocateTitle": { zh: "重新定位《{title}》", note: "System file picker title." },
  "notice.open.failed": "打开失败：{error}",
  "notice.delete.importing": "正在导入书籍，暂不能删除",
  "notice.delete.removing": "正在移除书籍…",
  "notice.delete.failed": "删除失败：{error}",
  "notice.delete.done.other": "已删除 {count} 本",
  "notice.delete.done.one": { zh: "已删除 {count} 本", note: "Singular form." },
  "notice.delete.partial": "删除失败 {count} 本：{errors}",
  "notice.bookmark.added": { zh: "已加入书签", max: 16 },
  "notice.bookmark.removed": { zh: "已移除书签", max: 16 },
  "notice.bookmark.saveFailed": "书签保存失败：{error}",
  "notice.bookmark.deleteFailed": "书签删除失败：{error}",
  "notice.progress.localWriteFailed": "阅读进度保存失败：本机恢复位置无法写入",
  "notice.progress.saving": "正在保存进度…",
  "notice.progress.saveFailed": "阅读进度保存失败：{error}",
  "notice.service.unavailable": "资料服务暂不可用：{error}",
  "notice.search.unbound": { zh: "书架中未绑定源文件", note: "Why a search hit cannot be opened." },
  "notice.index.rebuildWarning": "重新建立会清除现有全文索引，并重新处理全部可用书籍。",
  "notice.importBooks.untitled": { zh: "未命名书籍", note: "Fallback title." },
  "notice.importBooks.rebound": "此书已在书架，已更新本机源文件绑定；原有进度和笔记已保留",
  "notice.importBooks.alreadyImported": "此书已经被导入过了哦",
  "notice.importBooks.imported.other": "已导入 {count} 本",
  "notice.importBooks.imported.one": { zh: "已导入 {count} 本", note: "Singular form." },
  "notice.importBooks.duplicates": { zh: "重复 {count} 本：{names}", note: "{names} is a list of titles." },
  "notice.importBooks.duplicatesMore": { zh: "等书", note: "Appended after a shortened title list ('and others')." },
  "notice.importBooks.rebindNote": "（已更新 {count} 本源文件绑定，保留原有进度和笔记）",
  "notice.importBooks.failedList": "失败 {count} 本（{list}）",
  "notice.importBooks.title": { zh: "《{title}》", note: "A book title in a list; use your language's convention." },
  "notice.openFailure.noReason": "未收到具体错误原因，请重试；若仍失败，请保留现场反馈",
  "notice.openFailure.changed": { zh: "{message}。原书进度和笔记已保留；请选择原文件，或将修改后的文件导入为另一版本", note: "{message} is a backend explanation (may stay Chinese)." },
  "notice.openFailure.missing": { zh: "{message}。原书进度和笔记已保留；可重新导入原文件，无需先删除书架记录", note: "{message} is a backend explanation (may stay Chinese)." },
  "notice.loading.chapterFailed": "章节加载失败：{error}",
  "notice.loading.empty": "本章无可显示内容",
  "notice.loading.position": "准备阅读位置…",
  "notice.loading.chapter": "正在加载章节…",
  "notice.loading.layout": "正在准备排版…",
});
