import { defineMessages } from "../defineMessages";

/** Export/import of .epubsave archives: dialogs and the progress card. */
export const saveFile = defineMessages("saveFile", {
  "saveFile.phase.preparing": "正在准备",
  "saveFile.phase.reading": "正在读取资料",
  "saveFile.phase.extracting": "正在解析存档",
  "saveFile.phase.writing": "正在写入",
  "saveFile.phase.finalizing": "正在收尾",
  "saveFile.phase.copying": "正在写入目标",
  "saveFile.phase.committing": "正在提交到书库",
  "saveFile.phase.working": "进行中",
  "saveFile.progress.bytes": { zh: "{phase} {percent}% · {done} / {total}", note: "{done}/{total} are sizes like '3.2 MB'." },
  "saveFile.progress.processed": { zh: "{phase} · 已处理 {done}", note: "{done} is a size like '3.2 MB'." },
  "saveFile.progress.pending": { zh: "{phase}…", note: "Phase name followed by an ellipsis." },
  "saveFile.export.dialog": "导出存档",
  "saveFile.export.title": "导出存档",
  "saveFile.export.subtitle": "新格式为 .epubsave，包含可移植资料与所选书籍文件。",
  "saveFile.export.scope": "导出范围",
  "saveFile.export.all": "全库",
  "saveFile.export.selectedCount.other": { zh: "当前选中的书（{count} 本）", note: "{count} counts books." },
  "saveFile.export.selectedCount.one": { zh: "当前选中的书（{count} 本）", note: "Singular form ({count} is 1)." },
  "saveFile.export.selectedNone": "当前选中的书（无选中）",
  "saveFile.export.explain": "阅读资料包含进度、书签、笔记、收藏及文件夹；全库包含空文件夹，选中的书只带相关文件夹。附带书籍文件与资料范围是两个独立选择。",
  "saveFile.export.includeBooks": "附带书籍文件（默认关；开启后可在另一设备直接阅读）",
  "saveFile.cancel": { zh: "取消", max: 10 },
  "saveFile.export.confirm": "选择保存位置并导出",
  "saveFile.import.dialog": "导入存档预览",
  "saveFile.import.title": "导入存档预览",
  "saveFile.import.subtitle": { zh: "{source}；预览不会写入书库。", note: "{source} is a file name or 'Selected archive'." },
  "saveFile.import.selected": "已选择存档",
  "saveFile.import.bookCount": "存档资料书数",
  "saveFile.import.newBooks": "新资料数",
  "saveFile.import.attached": "实际附带书籍",
  "saveFile.import.missing": "待补书籍",
  "saveFile.import.conflicts": "进度分歧",
  "saveFile.import.missingList": { zh: "待补：{titles}", note: "{titles} is a list of book titles." },
  "saveFile.listSeparator": { zh: "、", note: "Separator between list items, e.g. ', ' in English." },
  "saveFile.import.more.other": { zh: " 等 {count} 本", note: "Appended after a shortened list: 'and N books in total'. Keep the leading space if needed." },
  "saveFile.import.more.one": { zh: " 等 {count} 本", note: "Singular form." },
  "saveFile.import.applyPreferences": "采用存档中的外观设置（只应用主题、字号、行距等白名单字段）",
  "saveFile.import.explain": "确认后会把资料并入当前书库；未附带文件的书保留原进度/笔记并显示为待补充书籍。",
  "saveFile.canceling": "正在取消…",
  "saveFile.import.confirm": "确认导入",
  "saveFile.progress.exporting": "正在导出存档",
  "saveFile.progress.reading": "正在读取存档",
  "saveFile.progress.committing": "正在提交到书库",
  "saveFile.progress.cancelingShort": "取消中…",
  "saveFile.progress.noCancel": "提交中不可取消",
  "saveFile.progress.tooLate": "已进入不可回退阶段，等待真实结果。",
  "saveFile.progress.committed": "提交已开始，关闭窗口也不会回滚。",
});
