import { defineMessages } from "../defineMessages";

/** Full-text search panel (current book / whole library) and the library index card. */
export const search = defineMessages("search", {
  "search.status.searching": { zh: "正在搜索 {processed}/{total} 章", note: "Progress while scanning chapters." },
  "search.status.complete": "搜索完成",
  "search.status.error": "搜索失败",
  "search.index.checking": "正在检查书库索引…",
  "search.index.checkingDetail": "只检查已有索引状态，不会读取或处理 EPUB。",
  "search.index.progress.other": { zh: "正在建立全文索引 {completed}/{total} 本", note: "{total} counts books." },
  "search.index.progress.one": { zh: "正在建立全文索引 {completed}/{total} 本", note: "Singular form ({total} is 1)." },
  "search.index.cancelProgress.other": "正在取消索引 {completed}/{total} 本",
  "search.index.cancelProgress.one": { zh: "正在取消索引 {completed}/{total} 本", note: "Singular form ({total} is 1)." },
  "search.index.cancelling": "正在取消…",
  "search.index.cancel": "取消",
  "search.index.current": { zh: "当前：{title}", note: "{title} is the book being indexed or a status." },
  "search.index.waiting": "正在等待当前任务结束…",
  "search.index.preparing": "准备中…",
  "search.index.confirm.title": "建立全部书籍索引",
  "search.index.partial.title": "书库索引尚未完成",
  "search.index.cancelled.title": "索引已取消",
  "search.index.error.title": "索引建立失败",
  "search.index.confirm.body": "建立全库索引会读取需要处理的 EPUB，期间可能占用较多 CPU 和内存，并需要一段时间。索引建立后会保留，后续搜索无需重复处理。",
  "search.index.partial.body": "已完成的书籍可以正常搜索；继续建立索引后，剩余书籍也会加入搜索范围。",
  "search.index.cancelled.body": "已完成的书籍仍然保留，可以继续搜索；需要时可从剩余书籍继续建立索引。",
  "search.index.error.body": "本次索引未能完成，已完成的书籍仍然保留。",
  "search.index.auto": { zh: "自动", max: 16 },
  "search.index.autoRecommended": { zh: "自动（推荐 {count}）", note: "Concurrency option; {count} is a number of workers.", max: 22 },
  "search.index.manual": { zh: "手动", max: 16 },
  "search.index.stats": "索引统计",
  "search.index.stats.total": { zh: "书库总数", note: "Followed by a bold number." },
  "search.index.stats.done": { zh: "已可搜索", note: "Followed by a bold number." },
  "search.index.stats.pending": { zh: "待处理", note: "Followed by a bold number." },
  "search.index.concurrency": "索引并发设置",
  "search.index.concurrency.label": "索引并发",
  "search.index.concurrency.less": "减少并发数",
  "search.index.concurrency.value": "索引并发数",
  "search.index.concurrency.more": "增加并发数",
  "search.index.cores": "检测到 {count} 个逻辑处理器",
  "search.index.concurrency.help": "自动推荐 {recommended}；手动最大 {maximum}。在可用时为系统至少保留 1 个逻辑处理器，且应用硬上限为 16；并发越高，占用的内存也越多。",
  "search.index.defer": "暂不建立",
  "search.index.skip": "暂不处理",
  "search.index.start": "开始建立索引",
  "search.index.resume": "继续建立索引",
  "search.results": "搜索结果",
  "search.truncated": "结果较多，仅显示前 {limit} 条",
  "search.dialog": "正文搜索",
  "search.drag.tip": "按住标题栏可自由拖动搜索窗口",
  "search.title": { zh: "正文搜索", max: 16 },
  "search.count.other": { zh: "{count} 条", note: "Result count badge.", max: 12 },
  "search.count.one": { zh: "{count} 条", note: "Singular result count.", max: 12 },
  "search.none": { zh: "无结果", max: 12 },
  "search.close": "关闭搜索",
  "search.scope": "搜索范围",
  "search.scope.current": { zh: "当前书", max: 12 },
  "search.scope.all": { zh: "全部书籍", max: 12 },
  "search.view": "当前书搜索文字",
  "search.view.display": { zh: "当前显示", note: "Search the text as displayed (after character conversion).", max: 12 },
  "search.view.original": { zh: "原文", note: "Search the book's original text.", max: 12 },
  "search.indexActions": "全文索引管理",
  "search.rebuild": "重新建立索引",
  "search.clearIndex": "清除索引",
  "search.placeholder.all": "搜索全部书籍正文",
  "search.placeholder.current": "搜索当前书正文",
  "search.clear": "清空搜索",
  "search.cancel": "取消",
  "search.errorDetail": { zh: "：{message}", note: "Appended after 'Search failed'; {message} is a raw technical detail." },
  "search.hint.all": "输入关键词搜索全部书籍的正文",
  "search.hint.current": "输入关键词搜索当前书的正文",
  "search.empty": "未找到匹配内容",
  "search.locating": "正在定位结果…",
});
