import { defineMessages } from "../defineMessages";

/** Shelf folders: folder cards, create/rename/dissolve/move dialogs and the open-folder sheet. Folder names are user data. */
export const shelfFolder = defineMessages("shelfFolder", {
  "shelfFolder.card.tip.other": { zh: "文件夹：{name}（{count} 本）", note: "Tooltip on a folder card." },
  "shelfFolder.card.tip.one": { zh: "文件夹：{name}（{count} 本）", note: "Singular form." },
  "shelfFolder.card.drop": { zh: "放入文件夹", note: "Overlay while dragging a book onto a folder.", max: 14 },
  "shelfFolder.options.tip": "文件夹选项",
  "shelfFolder.options": "文件夹选项：{name}",
  "shelfFolder.open": "打开文件夹",
  "shelfFolder.rename": { zh: "重命名", max: 12 },
  "shelfFolder.dissolve": { zh: "解散文件夹", note: "Remove the folder; books go back to the shelf.", max: 14 },
  "shelfFolder.bookCount.other": { zh: "{count} 本书", max: 12 },
  "shelfFolder.bookCount.one": { zh: "{count} 本书", note: "Singular form.", max: 12 },
  "shelfFolder.create.title": "新建文件夹",
  "shelfFolder.name.placeholder": "请输入文件夹名称…",
  "shelfFolder.cancel": { zh: "取消", max: 10 },
  "shelfFolder.creating": { zh: "创建中…", max: 10 },
  "shelfFolder.create": { zh: "创建", max: 10 },
  "shelfFolder.rename.title": "重命名文件夹",
  "shelfFolder.saving": { zh: "保存中…", max: 10 },
  "shelfFolder.confirm": { zh: "确定", max: 10 },
  "shelfFolder.dissolve.title": { zh: "解散文件夹“{name}”？", note: "Confirmation title; quote marks around the folder name." },
  "shelfFolder.dissolve.hint": "书籍将回到未归类，收藏、进度和笔记保留。",
  "shelfFolder.dissolving": { zh: "解散中…", max: 12 },
  "shelfFolder.move.oneBook": { zh: "《{title}》", note: "A single book title in the move dialog title; use your language's title convention." },
  "shelfFolder.move.books.other": "{count} 本书",
  "shelfFolder.move.books.one": { zh: "{count} 本书", note: "Singular form." },
  "shelfFolder.move.title": { zh: "移动 {target} 至", note: "{target} is a book title or 'N books'. A folder list follows." },
  "shelfFolder.move.current": "当前所在位置",
  "shelfFolder.move.root": "未归类（书架根目录）",
  "shelfFolder.move.currentBadge": { zh: "（当前）", max: 10 },
  "shelfFolder.move.count.other": { zh: "{count} 本", max: 10 },
  "shelfFolder.move.count.one": { zh: "{count} 本", note: "Singular form.", max: 10 },
  "shelfFolder.move.newPlaceholder": "新文件夹名称…",
  "shelfFolder.move.createAndSelect": { zh: "创建并选择", max: 14 },
  "shelfFolder.move.new": { zh: "新建文件夹", max: 14 },
  "shelfFolder.moving": { zh: "移动中…", max: 12 },
  "shelfFolder.move.confirm": { zh: "确定移动", max: 12 },
  "shelfFolder.modal": "文件夹：{name}",
  "shelfFolder.modal.count.other": { zh: "{count} 本", max: 10 },
  "shelfFolder.modal.count.one": { zh: "{count} 本", note: "Singular form.", max: 10 },
  "shelfFolder.modal.rename": "重命名文件夹",
  "shelfFolder.modal.close.tip": "关闭",
  "shelfFolder.modal.close": "关闭文件夹",
  "shelfFolder.modal.empty.touch": { zh: "文件夹暂无书籍，可在书籍“更多”菜单中选择“移动到文件夹”", note: "Quoted names refer to the book card 'More' menu and its 'Move to folder' item (shelf.card.moveToFolder)." },
  "shelfFolder.modal.empty.pointer": "文件夹暂无书籍，从书架将书拖入此处或移出",
  "shelfFolder.filter.search": { zh: "搜索{label}", note: "Placeholder: search within a filter list, e.g. 'Search authors'." },
  "shelfFolder.filter.none": "没有匹配项",
  "shelfFolder.filter.limited": "仅显示前 {count} 项，请搜索以缩小范围",
});
