import { defineMessages } from "../defineMessages";

/**
 * Shelf page frame: header, category tabs, folder dropdown, sort/density,
 * empty states, list-view table, delete confirmation and the batch toolbar.
 */
export const shelfMain = defineMessages("shelfMain", {
  "shelfMain.empty.hint.android": "导入 EPUB 后会出现在这里，点击上方“导入”从设备文件中选择",
  "shelfMain.empty.hint.desktop": "导入 EPUB 后会出现在这里，点击上方“导入”或直接将文件拖拽到窗口",
  "shelfMain.category.all": { zh: "全部", max: 10 },
  "shelfMain.category.reading": { zh: "正在读", max: 10 },
  "shelfMain.category.unread": { zh: "未读", max: 10 },
  "shelfMain.category.finished": { zh: "已读完", max: 10 },
  "shelfMain.category.favorites": { zh: "收藏", max: 10 },
  "shelfMain.category.withCount": { zh: "{label} ({count})", max: 16 },
  "shelfMain.selection.cancel": { zh: "取消", max: 8 },
  "shelfMain.selection.count.other": { zh: "已选 {count} 本", max: 14 },
  "shelfMain.selection.count.one": { zh: "已选 {count} 本", note: "Singular form.", max: 14 },
  "shelfMain.selection.none": { zh: "全选", max: 10 },
  "shelfMain.selection.clearAll": { zh: "取消全选", max: 10 },
  "shelfMain.brand": { zh: "书架", note: "Page title shown next to the logo.", max: 10 },
  "shelfMain.settings.mobile": "书架设置与更多",
  "shelfMain.search.mobile": "搜书名或作者",
  "shelfMain.search.clear": "清除搜索",
  "shelfMain.search.clear.tip": "清除搜索内容",
  "shelfMain.search.quick": { zh: "快速搜书名... (按 / 键聚焦)", note: "Placeholder; keep the '/' key hint." },
  "shelfMain.search.quick.label": "快速搜书名",
  "shelfMain.viewToggle": "视图模式切换",
  "shelfMain.view.grid": "网格视图",
  "shelfMain.view.list": "列表视图",
  "shelfMain.batch.enter.tip": "开启批量选择 (多选删除/移动/收藏)",
  "shelfMain.batch.enter": { zh: "批量选择", max: 12 },
  "shelfMain.settings": "书架设置与高级工具",
  "shelfMain.nav": "书架分类导航与排序",
  "shelfMain.category.choose": "选择分类与状态",
  "shelfMain.category.tabs": "阅读状态分流",
  "shelfMain.folders.choose": "选择或管理文件夹",
  "shelfMain.folders.fallback": { zh: "文件夹", max: 14 },
  "shelfMain.folders.count": { zh: "文件夹 ({count})", max: 16 },
  "shelfMain.folders.all": "全部藏书",
  "shelfMain.folders.unclassified": "未归类书籍",
  "shelfMain.folders.collapseCards": "收起书架文件夹卡片",
  "shelfMain.folders.expandCards": "在书架展开文件夹卡片",
  "shelfMain.folders.new": "新建文件夹",
  "shelfMain.folder.exit": "退出当前文件夹",
  "shelfMain.folder.name": { zh: "《{name}》", note: "Current folder name in the folder bar; use your language's quoting." },
  "shelfMain.folder.bookCount.other": "{count} 本书",
  "shelfMain.folder.bookCount.one": { zh: "{count} 本书", note: "Singular form." },
  "shelfMain.folder.actions": "文件夹操作",
  "shelfMain.folder.rename": { zh: "重命名", max: 10 },
  "shelfMain.folder.rename.tip": "重命名文件夹",
  "shelfMain.folder.dissolve": { zh: "解散", max: 8 },
  "shelfMain.folder.dissolve.tip": "解散文件夹",
  "shelfMain.sort": "书籍排序方式",
  "shelfMain.sort.recent": { zh: "排序：最近阅读", max: 16 },
  "shelfMain.sort.added": { zh: "排序：最近添加", max: 16 },
  "shelfMain.sort.title": { zh: "排序：书名排序", max: 16 },
  "shelfMain.sort.progress": { zh: "排序：阅读进度", max: 16 },
  "shelfMain.density.comfortable": { zh: "舒适", max: 8 },
  "shelfMain.density.standard": { zh: "标准", max: 8 },
  "shelfMain.density.compact": { zh: "紧凑", max: 8 },
  "shelfMain.density.tip": { zh: "排布密度：{current}，点按切换为{next}", note: "Tooltip on the density button." },
  "shelfMain.empty.title": "书架还是空的",
  "shelfMain.empty.import": "导入第一本书",
  "shelfMain.favorites.empty": "暂无收藏书籍",
  "shelfMain.favorites.hint": "点击书籍卡片左上角的星标即可将书籍加入收藏",
  "shelfMain.favorites.viewAll": "查看全部书籍",
  "shelfMain.folder.empty": "文件夹为空",
  "shelfMain.folder.emptyHint": "多选书籍或点击卡片菜单可将书籍移入此文件夹",
  "shelfMain.folder.back": "返回书架",
  "shelfMain.search.none": "没有找到匹配的内容",
  "shelfMain.search.noneHint": "换一个关键词或清除筛选条件试试",
  "shelfMain.search.clearQuery": "清除搜索词",
  "shelfMain.table.select": { zh: "选择", note: "Column header in selection mode.", max: 6 },
  "shelfMain.table.cover": { zh: "封面", max: 8 },
  "shelfMain.table.title.tip": "点击按书名排序",
  "shelfMain.table.title": { zh: "书名", max: 10 },
  "shelfMain.table.author": { zh: "作者", max: 10 },
  "shelfMain.table.progress.tip": "点击按进度排序",
  "shelfMain.table.progress": { zh: "进度", max: 10 },
  "shelfMain.table.size": { zh: "大小", max: 8 },
  "shelfMain.table.time.tip": "点击按阅读时间排序",
  "shelfMain.table.time": { zh: "阅读时间", max: 12 },
  "shelfMain.table.actions": { zh: "操作", max: 8 },
  "shelfMain.table.folderCount.other": { zh: "{count} 本", max: 10 },
  "shelfMain.table.folderCount.one": { zh: "{count} 本", note: "Singular form.", max: 10 },
  "shelfMain.table.folder": { zh: "文件夹", note: "Author column for a folder row.", max: 10 },
  "shelfMain.table.openFolder": "打开文件夹",
  "shelfMain.folders.summary": "文件夹 ({count})",
  "shelfMain.folders.collapse.tip": "收起文件夹目录",
  "shelfMain.folders.collapse": { zh: "收起", max: 8 },
  "shelfMain.merge": { zh: "将合并《{first}》与《{second}》入新文件夹", note: "Two book titles dropped onto each other create a folder." },
  "shelfMain.delete.many.other": "删除选中的 {count} 本书？",
  "shelfMain.delete.many.one": { zh: "删除选中的 {count} 本书？", note: "Singular form." },
  "shelfMain.delete.one": "从书架删除此书？",
  "shelfMain.delete.separator": { zh: "、", note: "Separator between book titles, e.g. ', '." },
  "shelfMain.delete.hint": "源文件不会被删除，但书签与本地进度将被移除。再次导入同一本书会恢复收藏和分类。",
  "shelfMain.delete.cancel": { zh: "取消", max: 10 },
  "shelfMain.delete.confirm": { zh: "确认删除", max: 12 },
  "shelfMain.drag.strip": "拖到这里移入文件夹",
  "shelfMain.drag.stripLabel": { zh: "移入文件夹", max: 14 },
  "shelfMain.dock": "批量操作栏",
  "shelfMain.dock.selected.other": { zh: "已选 {count} 本", max: 14 },
  "shelfMain.dock.selected.one": { zh: "已选 {count} 本", note: "Singular form.", max: 14 },
  "shelfMain.dock.hint": "请点击图书卡片进行选择",
  "shelfMain.dock.favorite": { zh: "收藏", note: "Tablet: icon above text; keep short.", max: 8 },
  "shelfMain.dock.favorite.tip": "加入收藏",
  "shelfMain.dock.unfavorite": { zh: "取消收藏", max: 10 },
  "shelfMain.dock.move": { zh: "移至文件夹", max: 12 },
  "shelfMain.dock.export.tip": "导出选中书籍为新存档",
  "shelfMain.dock.export": { zh: "导出", max: 8 },
  "shelfMain.dock.send.tip": "通过设备互传发给另一台设备",
  "shelfMain.dock.send": { zh: "发到设备", max: 10 },
  "shelfMain.dock.delete.tip": "从书架删除选中的书籍",
  "shelfMain.dock.delete": { zh: "删除", max: 8 },
  "shelfMain.dock.exit.tip": "退出多选",
  "shelfMain.dock.exit": { zh: "退出选择", max: 10 },
});
