import { defineMessages } from "../defineMessages";

/**
 * Shelf menu (settings drawer): search, filters, display settings, backup and
 * management rows. Bottom sheet on phones; select values are narrow (max ≈ 8).
 */
export const shelfMenu = defineMessages("shelfMenu", {
  "shelfMenu.dialog": "书架菜单",
  "shelfMenu.title": "书架菜单",
  "shelfMenu.bookCount.other": { zh: "{count} 本书", max: 14 },
  "shelfMenu.bookCount.one": { zh: "{count} 本书", note: "Singular form.", max: 14 },
  "shelfMenu.close": "关闭书架菜单",
  "shelfMenu.searchMode": "书架搜索模式",
  "shelfMenu.searchMode.metadata": { zh: "书名与作者", max: 14 },
  "shelfMenu.searchMode.body": { zh: "正文", note: "Search inside book text.", max: 10 },
  "shelfMenu.body.scope": "范围：全部书籍",
  "shelfMenu.body.clear": "清除正文搜索",
  "shelfMenu.search.placeholder": "搜索书名或作者",
  "shelfMenu.search.clear": "清除搜索",
  "shelfMenu.results": "搜索结果直达",
  "shelfMenu.results.found.other": "找到 {count} 本匹配书籍",
  "shelfMenu.results.found.one": { zh: "找到 {count} 本匹配书籍", note: "Singular form." },
  "shelfMenu.results.browse.tip": "在书架中浏览结果并收起菜单",
  "shelfMenu.results.browse": { zh: "在书架中浏览 ➔", note: "Keep the arrow." },
  "shelfMenu.results.none": { zh: "未找到与 “{query}” 相关的书籍", note: "{query} is what the user typed." },
  "shelfMenu.results.reading": { zh: "在读", max: 8 },
  "shelfMenu.results.unread": { zh: "未读", max: 8 },
  "shelfMenu.results.more": "仅显示前 20 本，可在书架中浏览全部 {count} 本",
  "shelfMenu.filters": "书籍筛选",
  "shelfMenu.allBooks": "全部书籍",
  "shelfMenu.filter.author": "作者",
  "shelfMenu.filter.title": "书名",
  "shelfMenu.filter.saved": "保存时间",
  "shelfMenu.filter.language": "语言",
  "shelfMenu.filter.clear": "清除筛选（{count}）",
  "shelfMenu.display": "显示设置",
  "shelfMenu.viewMode": "视图模式",
  "shelfMenu.viewMode.grid": { zh: "网格视图", max: 10 },
  "shelfMenu.viewMode.list": { zh: "列表视图", max: 10 },
  "shelfMenu.sort": "排列方式",
  "shelfMenu.sort.recent": { zh: "最近阅读", max: 10 },
  "shelfMenu.sort.added": { zh: "最近添加", max: 10 },
  "shelfMenu.sort.title": { zh: "书名", max: 10 },
  "shelfMenu.density": "排布密度",
  "shelfMenu.density.comfortable": { zh: "舒适", max: 10 },
  "shelfMenu.density.standard": { zh: "标准", max: 10 },
  "shelfMenu.density.compact": { zh: "紧凑", max: 10 },
  "shelfMenu.theme": "主题",
  "shelfMenu.theme.tip": "书架主题",
  "shelfMenu.theme.light": { zh: "浅色", max: 10 },
  "shelfMenu.theme.dark": { zh: "深色", max: 10 },
  "shelfMenu.theme.sepia": { zh: "羊皮纸", max: 10 },
  "shelfMenu.theme.gray": { zh: "深灰", max: 10 },
  "shelfMenu.motion": "界面动画",
  "shelfMenu.motion.full": { zh: "完整", max: 10 },
  "shelfMenu.motion.reduced": { zh: "简化", max: 10 },
  "shelfMenu.battery": "阅读电量",
  "shelfMenu.battery.tip": "阅读栏显示电量",
  "shelfMenu.show": { zh: "显示", max: 10 },
  "shelfMenu.hide": { zh: "隐藏", max: 10 },
  "shelfMenu.statusBar": "阅读时系统状态栏",
  "shelfMenu.statusBar.tip": "阅读时隐藏系统状态栏",
  "shelfMenu.keepScreenOn": "阅读时屏幕常亮",
  "shelfMenu.keepScreenOn.tip": "阅读时保持屏幕常亮，回到书架或切到后台即恢复系统熄屏",
  "shelfMenu.off": { zh: "关闭", max: 10 },
  "shelfMenu.on": { zh: "开启", max: 10 },
  "shelfMenu.backup": "备份与传输",
  "shelfMenu.lan": "设备互传",
  "shelfMenu.lan.detail": "同一 Wi‑Fi 下传书和阅读进度",
  "shelfMenu.export": "导出存档",
  "shelfMenu.export.detail": "保存为 .epubsave 文件",
  "shelfMenu.importArchive": "导入存档",
  "shelfMenu.importArchive.detail": "合并存档里的书和阅读资料",
  "shelfMenu.importLegacy": "导入旧版 JSON 存档",
  "shelfMenu.importLegacy.detail": "兼容早期版本导出的存档",
  "shelfMenu.manage": "管理",
  "shelfMenu.batch": "批量选择",
  "shelfMenu.batch.detail": "多选后收藏、移动、导出或删除",
  "shelfMenu.cache": "缓存与存储",
  "shelfMenu.cache.detail": "查看占用，清除全文索引",
  "shelfMenu.about": "关于",
  "shelfMenu.azRail": "首字母快速索引",
  "shelfMenu.azRail.jump": "跳转到首字母 {letter}",
  "shelfMenu.language.zh": "中文",
  "shelfMenu.language.ja": "日语",
  "shelfMenu.language.en": "英语",
  "shelfMenu.language.ko": "韩语",
  "shelfMenu.language.fr": "法语",
  "shelfMenu.language.de": "德语",
  "shelfMenu.language.es": "西班牙语",
  "shelfMenu.language.ru": "俄语",
  "shelfMenu.language.unknown": "未知语言",
});
