import { defineMessages } from "../defineMessages";

/**
 * Shelf main view: import button and menu, the "continue reading" card and book
 * cards. Book titles and authors are user data and never go through this catalog.
 */
export const shelf = defineMessages("shelf", {
  "shelf.import.tip": "导入 EPUB 图书到书架",
  "shelf.import.short": { zh: "导入", note: "Phone import button.", max: 8 },
  "shelf.import.books": { zh: "导入图书", note: "Main import button; other texts refer to it by this name.", max: 14 },
  "shelf.import.menu.tip": "导入图书或文件夹",
  "shelf.import.more": "更多导入方式",
  "shelf.import.menu": "导入方式",
  "shelf.import.books.detail": "选择一本或多本 EPUB",
  "shelf.import.folder": { zh: "导入文件夹", max: 18 },
  "shelf.import.folder.detail": "按目录自动整理到书架文件夹",
  "shelf.import.dropHint": "也可以把 EPUB 文件直接拖到书架上",
  "shelf.cover.initialFallback": { zh: "书", note: "One character drawn on a placeholder cover when the title is empty.", max: 1 },
  "shelf.time.justNow": "刚刚",
  "shelf.time.minutesAgo.other": "{count} 分钟前",
  "shelf.time.minutesAgo.one": { zh: "{count} 分钟前", note: "Singular form." },
  "shelf.time.hoursAgo.other": "{count} 小时前",
  "shelf.time.hoursAgo.one": { zh: "{count} 小时前", note: "Singular form." },
  "shelf.time.yesterday": "昨天",
  "shelf.resume.chapter": { zh: "第 {n} 章 · {progress}", note: "Collapsed 'continue' card: chapter number and progress like '34%'.", max: 22 },
  "shelf.resume.open": { zh: "打开《{title}》", note: "Tooltip; 《》 marks a book title — use the target language's convention." },
  "shelf.resume.continue": { zh: "继续", note: "Compact continue-reading button.", max: 8 },
  "shelf.resume.expand.tip": "展开 (显示封面与详细进度)",
  "shelf.resume.expand": "展开正在阅读",
  "shelf.resume.reading": { zh: "正在阅读", max: 14 },
  "shelf.resume.lastAt": { zh: "上次读到：{place}", note: "{place} is the chapter/progress text." },
  "shelf.resume.more.tip": "查看最近在读书籍（最多10本）",
  "shelf.resume.more": { zh: "更多在读 ({count})", max: 18 },
  "shelf.resume.openBook": { zh: "开书", note: "Small button: open this book.", max: 8 },
  "shelf.resume.continueReading.tip": "继续阅读当前书籍 (按 Space 或 Enter 一键开书)",
  "shelf.resume.continueReading": { zh: "继续阅读", max: 14 },
  "shelf.resume.collapse.tip": "收起 (折叠为单行)",
  "shelf.resume.collapse": "收起正在阅读",
  "shelf.unknownAuthor": "未知作者",
  "shelf.card.dropToCreateFolder": "松手新建文件夹",
  "shelf.card.unfavorite": "取消收藏",
  "shelf.card.favorite": "加入收藏",
  "shelf.card.unfavoriteBook": "取消收藏：{title}",
  "shelf.card.favoriteBook": "加入收藏：{title}",
  "shelf.card.reimport": { zh: "需重新导入", note: "Badge on a cover: the file must be imported again (Android).", max: 10 },
  "shelf.card.sourceMissing": { zh: "源文件缺失", note: "Badge on a cover: the linked file is missing.", max: 10 },
  "shelf.card.new": { zh: "新", note: "Tiny badge on a newly added book.", max: 4 },
  "shelf.card.reading": { zh: "在读", note: "Tiny badge: currently reading.", max: 8 },
  "shelf.card.progress": "阅读进度 {percent}%",
  "shelf.card.more.tip": "更多选项",
  "shelf.card.more": "更多书籍选项：{title}",
  "shelf.card.fullTitle": "完整书名：{title}",
  "shelf.card.open": "打开阅读",
  "shelf.card.moveToFolder": "移至文件夹",
  "shelf.card.removing": "正在移出…",
  "shelf.card.removeFromFolder": "从文件夹移除",
  "shelf.card.delete": "从书架删除",
  "shelf.card.readSuffix": { zh: " 已读", note: "Appended after a percentage, e.g. '42% read'. Keep the leading space if your language needs it." },
  "shelf.card.unread": { zh: "未读", max: 8 },
  "shelf.progress.pending": { zh: "待统计", note: "Progress not computed yet.", max: 10 },
  "shelf.table.select": "选择 {title}",
  "shelf.table.more": "更多选项：{title}",
  "shelf.timeSegment.today": "今天",
  "shelf.timeSegment.last7Days": "最近 7 天",
  "shelf.timeSegment.last30Days": "最近 30 天",
  "shelf.timeSegment.thisYear": "今年",
  "shelf.timeSegment.older": "更早",
});
