import { defineMessages } from "../defineMessages";

/** Reader side drawer: table of contents, bookmarks and notes tabs. */
export const sidebar = defineMessages("sidebar", {
  "sidebar.unknownTime": "未知时间",
  "sidebar.toc.unavailable": { zh: "无法使用：{href}", note: "Tooltip on a broken TOC entry; {href} is the raw link." },
  "sidebar.toc.noLink": "无有效链接",
  "sidebar.toc.untitled": "(无标题)",
  "sidebar.tab.toc": { zh: "目录", max: 10 },
  "sidebar.tab.bookmarks": { zh: "书签", max: 10 },
  "sidebar.tab.notes": { zh: "笔记", max: 10 },
  "sidebar.tab.count": { zh: "{label} ({count})", note: "Tab label with item count, e.g. 'Notes (3)'." },
  "sidebar.drawer": "阅读导航与笔记抽屉",
  "sidebar.unpin.tip": "取消固定（浮动遮罩模式）",
  "sidebar.pin": "固定驻留侧边栏",
  "sidebar.unpin": "取消固定",
  "sidebar.close.tip": "关闭侧边栏 (Esc)",
  "sidebar.close": "关闭侧边栏",
  "sidebar.toc.filter": { zh: "过滤章节...", note: "Placeholder of the chapter filter input." },
  "sidebar.toc.filter.label": "过滤目录章节",
  "sidebar.toc.filter.clear": "清除过滤",
  "sidebar.toc.empty": "本书暂无目录",
  "sidebar.toc.noMatch": "无匹配章节",
  "sidebar.bookmarks.empty": "暂无书签",
  "sidebar.bookmarks.emptyTip": { zh: "按 Ctrl+B 或顶栏 🔖 标记当前页", note: "Keep the shortcut and the emoji." },
  "sidebar.bookmark.noText": "（无书签文字）",
  "sidebar.bookmark.addedAt": { zh: "添加于 {time}", note: "{time} is a localized date/time." },
  "sidebar.bookmark.delete.tip": "删除此书签",
  "sidebar.bookmark.delete": "删除书签",
  "sidebar.notes.empty": "暂无划线与笔记",
  "sidebar.notes.emptyTip": "在正文选中文本即可添加笔记",
  "sidebar.note.quote": { zh: "“{text}”", note: "Quotes around the user's highlighted text; use the target language's quote marks." },
  "sidebar.note.edit": "编辑",
  "sidebar.note.confirmDelete": "确认删除？",
  "sidebar.note.delete": "删除",
  "sidebar.note.cancel": "取消",
});
