import { defineMessages } from "../defineMessages";

/** Reader top bar: buttons are icon-only on phones, so most strings are tooltips/aria labels. */
export const titlebar = defineMessages("titlebar", {
  "titlebar.tools.hide": "隐藏阅读工具",
  "titlebar.tools.show": "显示阅读工具",
  "titlebar.backToShelf.tip": { zh: "返回书架 (Esc)", note: "Tooltip; keep the key name in parentheses." },
  "titlebar.backToShelf": "返回书架",
  "titlebar.shelf": { zh: "书架", note: "Short button text next to the back icon.", max: 8 },
  "titlebar.sidebar.tip": { zh: "切换目录与书签侧边栏 (Ctrl+T)", note: "Tooltip; keep the shortcut." },
  "titlebar.sidebar": "切换侧边栏",
  "titlebar.toc": { zh: "目录", note: "Short button text.", max: 8 },
  "titlebar.appName": { zh: "EPUB 阅读器", note: "Shown when a book has no title." },
  "titlebar.sidebar.tipCompact": { zh: "切换侧边栏目录与书签 (Ctrl+T)", note: "Tooltip; keep the shortcut." },
  "titlebar.appearance": "外观与排版设置",
  "titlebar.search.tip": { zh: "搜索正文 (Ctrl+F)", note: "Tooltip; keep the shortcut." },
  "titlebar.search": "搜索正文",
  "titlebar.bookmark.remove.tip": "移除当前页书签 (Ctrl+B)",
  "titlebar.bookmark.add.tip": "添加当前页书签 (Ctrl+B)",
  "titlebar.bookmark.remove": "移除当前页书签",
  "titlebar.bookmark.add": "添加当前页书签",
  "titlebar.bookmarks.all.tip": "查看所有书签 (Ctrl+Shift+B)",
  "titlebar.bookmarks.all": "查看所有书签",
  "titlebar.fullscreen.exit.tip": "退出全屏 (F11 / Esc)",
  "titlebar.fullscreen.enter.tip": "全屏沉浸阅读 (F11)",
  "titlebar.fullscreen.exit": "退出全屏",
  "titlebar.fullscreen.enter": "全屏阅读",
  "titlebar.zen.on.tip": { zh: "顶栏当前为自动隐藏沉浸模式 (点击固定常驻)", note: "Tooltip: the bar auto-hides now; clicking pins it." },
  "titlebar.zen.off.tip": { zh: "顶栏当前已固定常驻 (点击开启自动隐藏沉浸模式)", note: "Tooltip: the bar is pinned now; clicking makes it auto-hide." },
  "titlebar.zen.pin": "固定常驻顶栏",
  "titlebar.zen.autoHide": "开启自动隐藏沉浸",
  "titlebar.ai": "AI 助手",
  "titlebar.diagnostics": "查看问题与诊断日志",
  "titlebar.window": { zh: "窗口控制", note: "Windows desktop window buttons group label." },
  "titlebar.minimize": "最小化",
  "titlebar.maximize.disabled": "全屏模式下不可最大化",
  "titlebar.restore": "向下还原",
  "titlebar.maximize": "最大化",
  "titlebar.close": "关闭",
  "titlebar.progress.toggleToc": "切换章节目录",
  "titlebar.progress.tip": { zh: "阅读进度：{percent}% (点击切换章节目录)", note: "Tooltip on the progress pill." },
  "titlebar.progress.chapter": { zh: "第 {current}/{total} 章", note: "Chapter position badge, e.g. 'Ch. 3/30'.", max: 14 },
});
